### ISSUE TITLE
real power only

### ISSUE THREAD

**Issue by widedh** [nilmtk/nilm_metadata#30]
Hello,

I'd like to use NILMTK for my own input data from my smart plug which deliver a pulse for each 1Wh consumed and then I calculate the real power consumption. 
So,  I have only the real power consumption. My question is it is possible to use this toolkit and how? And about the metadata that I have to build for my own data, is there any tool to help building it? 
I will be grateful if someone can help me.
Thank you very much.

**Comment by nipunbatra** [comment]
There is ample documentation available.  I'd advise you to refer that
before opening an issue.

On 28 Jun 2017 21:13, "widedh" <notifications@github.com> wrote:

Hello,

I'd like to use NILMTK for my own input data from my smart plug which
deliver a pulse for each 1Wh consumed and then I calculate the real power
consumption.
So, I have only the real power consumption. My question is it is possible
to use this toolkit and how? And about the metadata that I have to build
for my own data, is there any tool to help building it?
I will be grateful if someone can help me.
Thank you very much.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nilmtk/nilm_metadata/issues/30>, or mute the thread
