### ISSUE TITLE
please how can I import the redd.h5 metadata into Matlab

### ISSUE THREAD

**Issue by Jonas-code** [nilmtk/nilm_metadata#36]

**Comment by PMeira** [comment]
If you read want the **META**data, it's easier to process the YAML files at https://github.com/nilmtk/nilmtk/tree/master/nilmtk/dataset_converters/redd/metadata

For the data itself, it should be easier to handle the original CSV files instead of the HDF5 container.

**Comment by PMeira** [comment]
@Jonas-code An alternative approach: https://medium.com/@nipun_batra/interfacing-nilm-algorithms-written-in-matlab-with-nilmtk-31afbf60ed1e

**Comment by Jonas-code** [comment]
Thank you @PMeira but I would like to extract data from  metadata  in hdf5 format only in Matlab without going through python or Ipython

**Comment by nipunbatra** [comment]
@Jonas-code I would suggest you to look into reading HDF5 files in Matlab. Also look at https://github.com/nilmtk/nilm_metadata/blob/master/nilm_metadata/convert_yaml_to_hdf5.py

I'm afraid that beyond that we won't be able to support on this thread.

**Comment by Jonas-code** [comment]
Thank you @nipunbatra

**Comment by PMeira** [comment]
@Jonas-code You can easily read the metadata attributes from the HDF, but I'm not sure how useful this is:

    h5readatt('redd.h5', '/', 'metadata')
    h5readatt('redd.h5', '/building1', 'metadata')
    ...

If you want to try loading the YAML files directly instead of reading the HDF metadata, there are some projects like https://github.com/ewiger/yamlmatlab that use Java classes (which MATLAB support) to load the files, returning a structure.

Neither options seem ideal but they might real you in your goal. As Nipun said, we probably can't help beyond that.

**Comment by Jonas-code** [comment]
Thank you very much for help @PMeira    ; I would like to use that data with Matlab algorithms, so I wanted to write functions that can extract that data.
